export const mockGames = [
  {
    id: '1',
    title: "Devil's Drizzle",
    slug: 'devils-drizzle',
    shortDescription: 'Plataformer 2D dark cute onde um garoto persegue seu guarda-chuva e enfrenta demônios sumérios.',
    fullDescription: 'Um platformer 2D de ação com estética fofa e sombria, onde um garoto persegue seu guarda-chuva e acaba enfrentando demônios sumérios. Pule, dê dash e destrua inimigos em fases variadas iluminadas apenas por um amuleto relampejante, com boss fights e escolhas que mudam o final.',
    coverUrl: 'https://picsum.photos/seed/devils/300/400',
    trailerUrl: null,
    demoUrl: 'https://itch.io',
    status: 'FEATURED',
    genre: 'Plataformer 2D',
    studioName: 'Rainy Studio',
    launchWindow: 'Q3 2025',
  },
  {
    id: '2',
    title: 'Alien Strike',
    slug: 'alien-strike',
    shortDescription: 'Shooter retrô com estética synthwave. Destrua invasores com seu time.',
    fullDescription: 'Shooter cooperativo retrô em neon com estética synthwave dos anos 80. Reúna um time de agentes especiais e destrua ondas de invasores alienígenas em cenários urbanos estilizados.',
    coverUrl: 'https://picsum.photos/seed/alien/300/400',
    trailerUrl: null,
    demoUrl: 'https://itch.io',
    status: 'FEATURED',
    genre: 'Shooter',
    studioName: 'NeonByte Games',
    launchWindow: 'Q4 2025',
  },
  {
    id: '3',
    title: 'Sunny Trails',
    slug: 'sunny-trails',
    shortDescription: 'Aventura colorida por trilhas tropicais com combate e puzzles.',
    fullDescription: 'Explore trilhas tropicais vibrantes em uma aventura de ação e puzzle. Enfrente criaturas, resolva enigmas ambientais e descubra os segredos escondidos nas ilhas.',
    coverUrl: 'https://picsum.photos/seed/sunny/300/400',
    trailerUrl: null,
    demoUrl: 'https://itch.io',
    status: 'AVAILABLE',
    genre: 'Aventura',
    studioName: 'Tropik Dev',
    launchWindow: 'Q1 2026',
  },
  {
    id: '4',
    title: 'Alabaster Dawn',
    slug: 'alabaster-dawn',
    shortDescription: 'RPG de fantasia com visuais aquarela e sistemas de escolhas profundas.',
    fullDescription: 'Um RPG de fantasia épica com arte em aquarela única e sistemas de escolhas morais que moldam o destino do mundo.',
    coverUrl: 'https://picsum.photos/seed/alabaster/300/400',
    trailerUrl: null,
    demoUrl: null,
    status: 'COMING_SOON',
    genre: 'RPG',
    studioName: 'Chalk & Ember',
    launchWindow: 'Q2 2026',
  },
  {
    id: '5',
    title: 'Scavland',
    slug: 'scavland',
    shortDescription: 'Survival horror atmosférico onde sua única luz é uma lanterna.',
    fullDescription: 'Explore instalações abandonadas em total escuridão com apenas uma lanterna. Cada sombra esconde algo. Cada som importa.',
    coverUrl: 'https://picsum.photos/seed/scavland/300/400',
    trailerUrl: null,
    demoUrl: null,
    status: 'COMING_SOON',
    genre: 'Horror',
    studioName: 'DarkCell Studio',
    launchWindow: 'Q2 2026',
  },
  {
    id: '6',
    title: 'Canvas Savant',
    slug: 'canvas-savant',
    shortDescription: 'Puzzle artístico onde você pinta o cenário para resolver enigmas.',
    fullDescription: 'Use pincéis mágicos para alterar o cenário e resolver puzzles únicos. A arte é tanto o ambiente quanto a solução.',
    coverUrl: 'https://picsum.photos/seed/canvas/300/400',
    trailerUrl: null,
    demoUrl: 'https://itch.io',
    status: 'AVAILABLE',
    genre: 'Puzzle',
    studioName: 'Brushwork Labs',
    launchWindow: 'Q3 2025',
  },
]
